import serial

PARITY_NONE = serial.PARITY_NONE
BYTE_SOF = b'\x02'
BYTE_EOF = b'\x03'
BYTE_CMD_POLL = b'\x01'
BYTE_CRC = b'\xFF'
BYTE_LEN_POLL = b'\x0D'
BYTE_LEN_DISPENSE = b'\x08'
BYTESIZE_DATA_POLL = 10
STATE_FIND_SOF = 'SOF'
STATE_FIND_LEN = 'LEN'
STATE_FIND_DATA = 'DATA'
STATE_FIND_EOF = 'EOF'
PACKAGE_ERROR = -1
PACKAGE_OK = 0
